name: ekovin
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - cfgrib
  - pip
  - pip:
      - numpy<2
      - requests
      - xarray
      - matplotlib
      - catboost
      - pandas
      - streamlit
